name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull bokeefe96/b-mono-image:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-docker-hub || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-docker-hub bokeefe96/b-mono-image
    - name: Copy index.html to Nginx directory
      run: scp -i /path/to/your/private/key -o StrictHostKeyChecking=no index.html ubuntu@EC2_INSTANCE_IP:/var/www/html/
